### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by luckysori** [ElementsProject/elements-miniscript#10]
Firstly, we are really benefiting from your library in [our project](https://github.com/comit-network/baru), so thanks for that!

After introducing the git dependency we are no longer able to release to `crates.io`. Do you know when you will be releasing `elements-miniscript` to `crates.io`?

**Comment by sanket1729** [comment]
Yes, sure. I will release make a release

**Comment by sanket1729** [comment]
Currently, this is blocked on rust-miniscript release for bitcoin 0.26 types. But once that is done, I will immediately make a release for this.

**Comment by luckysori** [comment]
You've done it, thank you!
