### ISSUE TITLE
Miniscript MinimalIF bug?

### ISSUE THREAD

**Issue by tiero** [ElementsProject/elements-miniscript#20]
Are we sure elements miniscript is also safe from MinimalIF bug?
https://github.com/rust-bitcoin/rust-miniscript/blob/master/doc/security_report_2022_04_20.md

**Comment by sanket1729** [comment]
`elements-miniscript` is affected by the bug. We will update the repository next week with detailed instructions.

**Comment by sanket1729** [comment]
Sorry for the delay in fixing this. The latest master should have the bug fixed. We will have a release shortly.
