### ISSUE TITLE
`elements_miniscript::confidential::slip77` duplicates code from `elements::slip77`

### ISSUE THREAD

**Issue by LeoComandini** [ElementsProject/elements-miniscript#54]
Those have small differences but they are basically the same thing, 
which one should be used by downstream libraries?

**Comment by apoelstra** [comment]
`confidential::slip77` should be used downstream. We can delete the top-level module. Maybe we should re-export it though so that it has a more obvious location.

**Comment by RCasatta** [comment]
Closing since it has been removed from rust-elements

**Comment by apoelstra** [comment]
Closing. Though it may make sense to open an issue to move `slip77` specifically back. Unsure. My feeling is that we want to discourage slip77 going forward in favor of "CT descriptors".
