### ISSUE TITLE
Covenant extension parse example

### ISSUE THREAD

**Issue by louisinger** [ElementsProject/elements-miniscript#79]
given the `examples/parse.rs` file, I'm trying to decode descriptor using covenant extensions.

```rust
let info = miniscript::Descriptor::<bitcoin::PublicKey, extensions::CovenantExt<extensions::CovExtArgs>>::from_str(
      "eltr(02289715c2c4038285fb4fc688a74577eef1c069435ceb58d2c33957f30e2f7fec,and_v(v:pk(02289715c2c4038285fb4fc688a74577eef1c069435ceb58d2c33957f30e2f7fec), value_eq(out_value(0), out_value(1))))"
)
```

it fails with "Error: unexpected «value_eq(2 args) while parsing Miniscript»" error.
Is it possible to add an example with introspections tokens in `parse.rs` ?

**Comment by apoelstra** [comment]
When I run this locally, I get the same error as you, but removing the spaces fixes it.

**Comment by louisinger** [comment]
indeed... I was using the `ValueExpr` in the wrong way in my original testing descriptor:
```
value_eq(out_value(0),0000000000000000))) // explicit value without prefix
```
it led to the error "unexpected value_eq" error. my bad. I close the issue

**Comment by apoelstra** [comment]
Awesome, happy to help!
