### ISSUE TITLE
`to_string_no_chksum` returns debug representation instead of the descriptor string without the checksum?

### ISSUE THREAD

**Issue by RCasatta** [ElementsProject/elements-miniscript#85]
https://github.com/ElementsProject/elements-miniscript/blob/9425f2e699418f549ac73c5042a6a9bebfb038e8/src/descriptor/mod.rs#L438

**Comment by apoelstra** [comment]
Dupe of https://github.com/ElementsProject/elements-miniscript/issues/34 ... but I could have sworn I fixed this. Thanks for the poke. I will investigate.
